### ISSUE TITLE
Declarative configuration

### ISSUE THREAD

**Issue by affanshahid** [nokia/kong-oidc#136]
Does this plugin support Kong's DB-less mode through a configuration file? If so how should I define the options, currently I am getting errors in my config file about `unknown_properties`

**Comment by gwaldisp** [comment]
Based on the information here it looks like it’s not supported:

https://docs.konghq.com/1.3.x/db-less-and-declarative-config/#plugin-compatibility <https://docs.konghq.com/1.3.x/db-less-and-declarative-config/#plugin-compatibility>

**Comment by affanshahid** [comment]
It does seem to be supported and working, I just had to change the configuration a bit, perhaps this could be documented. My config now looks likes this:

```yml
services:
  - name: config
    url: http://example.com
    # Entities can store tags as metadata
    tags:
      - config
    # Entities that have a foreign-key relationship can be nested:
    routes:
      - name: config-api
        paths:
          - /config
        strip_path: true
        # preserve_host: true
    plugins:
      - name: cors
      - name: oidc
        config: 
          client_secret: secret
          client_id: kong 
          bearer_only: 'yes'
          realm: kong
          introspection_endpoint: http://mykeycloak.com/auth/realms/experimental/protocol/openid-connect/token/introspect 
          discovery: http://mykeycloak.com/auth/realms/master/.well-known/openid-configuration

```
