### ISSUE TITLE
Anormal level of request on the open id provider (keycloak)

### ISSUE THREAD

**Issue by samsja** [nokia/kong-oidc#142]
Hey,

i am testing this open id plugin and it worked great !

I am using keycloak as the open id provider in a gce cluster with k8s ( v1.1.2) and kong (1.3) with ingress controller (0.6.0)

However, with this plugin enable I am seeing a constant 1 request per seconds activity on my keycloak service. I thought that this plugin would make some request only when it needed to do some authentification when someone try to use a protected service .

![Screenshot from 2019-12-11 15-04-37](https://user-images.githubusercontent.com/55492238/70628060-b25d9080-1c27-11ea-964e-5293bb76ac89.png)

the period where there are'nt any request is when I stoped the plugin.

My plugin conf:

```yaml

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oid
config:
  client_id: CLIENT_NAME
  client_secret: CLIENT_SECRET
  discovery: https://path_to_my_keycloak.com/auth/realms/my_realm/.well-known/openid-configuration
plugin: oidc

```
Thanks in advance !
